###
http://localhost:5000

###
PATCH http://localhost:5000/users/3/tickets/8775626917
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkVXNlciI6MywiZmlyc3ROYW1lIjoic2FtcGxlIiwibGFzdE5hbWUiOiJ0ZXN0IiwicGFzc3dvcmQiOiIkMmIkMTAkemlGTWZpZHFJT2dMMnQyQmNhUGFqT3pkNnczVTU3VDR3NDFwaVVSNzNPeU9sTjZ2L09qWGkiLCJlbWFpbCI6InNhbXBsZUBmYXRib2FyLnNpdGUiLCJwaG9uZSI6IjA2MTIzNDU2NzkiLCJyb2xlIjoiQ0xJRU5UIiwic3RhdGUiOiJPRkZMSU5FIn0sImlhdCI6MTU3NDAwOTMzNn0.1RduZqriieXCOPGMgutBrgnePiKgVhMb1uhJFjamm_M

###
http://localhost:5000/tickets/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkVXNlciI6MSwiZmlyc3ROYW1lIjoiZmF0Ym9hciIsImxhc3ROYW1lIjoiZmF0Ym9hciIsInBhc3N3b3JkIjoiJDJiJDEwJDQvMnlhbEZoR2I1czRvTEJLeDFFQXU4VVNNYkREVVdiSEJ6RW5EQ3dMdXhWN2pGeXBKSlFlIiwiZW1haWwiOiJhZG1pbkBmYXRib2FyLnNpdGUiLCJwaG9uZSI6IjA2MTIzNDU2NzgiLCJyb2xlIjoiQURNSU4iLCJzdGF0ZSI6Ik9GRkxJTkUifSwiaWF0IjoxNTczNTAzNjc5fQ.j6ONNEz3RTYSXF6Ex_wjkzGyts12o0f-cFselFAJPqk

###
POST http://localhost:5000/auth/register
content-type: application/json

{
    "firstName": "sample",
    "lastName": "test",
    "password": "fatroot",
    "email": "sample@fatboar.site",
    "phone": "0612345679"
}

###
POST http://localhost:5000/auth/login
content-type: application/json

{
    "email": "sample@fatboar.site",
    "password": "fatroot"
}

###
PUT http://localhost:5000/tickets/2100865456
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkVXNlciI6MSwiZmlyc3ROYW1lIjoiZmF0Ym9hciIsImxhc3ROYW1lIjoiZmF0Ym9hciIsInBhc3N3b3JkIjoiJDJiJDEwJDQvMnlhbEZoR2I1czRvTEJLeDFFQXU4VVNNYkREVVdiSEJ6RW5EQ3dMdXhWN2pGeXBKSlFlIiwiZW1haWwiOiJhZG1pbkBmYXRib2FyLnNpdGUiLCJwaG9uZSI6IjA2MTIzNDU2NzgiLCJyb2xlIjoiQURNSU4iLCJzdGF0ZSI6Ik9GRkxJTkUifSwiaWF0IjoxNTczNTczNzgxfQ.4rsWnXesmRx354wWiaK5NCOicw3Cyqt3HQlxVFpjwss

###
https://api.stage.fatboar.site

###
POST https://api.stage.fatboar.site/register
content-type: application/json

{
    "first_name": "sample",
    "last_name": "test",
    "email": "admin@fatboar.site",
    "password": "fatroot"
}