###
http://localhost:5000

###
POST http://localhost:5000/register
content-type: application/json

{
    "first_name": "sample",
    "last_name": "test",
    "email": "sample@mail.com",
    "password": "test"
}