version: '3'
services:
  api:
    container_name: fatboar-back-build
    build: ./api
    image: fatboar-back_build
    ports:
      - '3001:3000'
      - '9230:9229'
  postgres-db:
    container_name: fatboar-db-build
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgresql_build:/var/lib/postgresql
  client:
    container_name: fatboar-front-build
    build: ./client
    image: fatboar-front_build
    ports:
      - '3002:3000'