version: '3'
services:
  api:
    build: ./api
    ports:
      - '3001:3000'
      - '9229:9229'
  postgres-db:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql
  client:
    build: ./client
    ports:
      - '3000:3000'