version: '3'
services:
  api:
    container_name: fatboar-back-build
    build: ./api
    image: fatboar-back_build
    ports:
      - '3001:3000'
      - '9230:9229'
    networks: 
      - fatboar-build
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
      - NODE_ENV=${NODE_ENV}
  postgres-db:
    container_name: fatboar-db-build
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks: 
      - fatboar-build
  client:
    container_name: fatboar-front-build
    build: ./client
    image: fatboar-front_build
    ports:
      - '3002:3000'
networks: 
  fatboar-build: