version: '3'
services:
  api:
    container_name: fatboar-back
    depends_on:
      - postgres-db
  postgres-db:
    container_name: fatboar-db
    hostname: postgres
    image: postgres:11.5-alpine
  client:
    container_name: fatboar-front
networks:
  web:
    external:
      name: web
volumes:
  node_modules: