version: '3'
services:
  api:
    container_name: docker-node-postgres
    restart: always
    build: ./api
    depends_on:
      - postgres-db
  postgres-db:
    container_name: postgres
    hostname: postgres
    image: postgres:alpine
    # volumes:
    #   - /var/lib/postgresql:/var/lib/postgresql
  db_gui:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres-db
  # client:
  #   container_name: react
  #   build: ./client
  #   image:
    # ports:
    #   - '27017:27017'
volumes:
  reserved: