# il faut ajouter la configuration de traefik
# Et voir s'il y a d'autres éléments exclusifs à la prod/stage
version: '3'
services:
  client:
    labels:
    - "traefik.enable=true"
    - "traefik.backend=traefik"
    - "traefik.frontend.rule=Host:${CLIENT_URL}" #fatboar.site
    - "traefik.port=${CLIENT_PORT}"
    - "traefik.docker.network=web"
  api:
    labels:
    - "traefik.enable=true"
    - "traefik.backend=traefik"
    - "traefik.frontend.rule=Host:${API_URL}" #fatboar.site/api ou api.fatboar.site
    - "traefik.port=${API_PORT}"
    - "traefik.docker.network=web"