version: '3'
services:
  api:
    image: node:10.16.3-alpine
    volumes:
      - './api:/usr/src/app'
      - 'node_modules:/usr/src/app/node_modules'
    ports:
      - '3000:3000'
      - '9229:9229'
    working_dir: /usr/src/app
    command: npm start
    environment:
      - NPM_CONFIG_PREFIX=/home/node/.npm-global
  postgres-db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # volumes:
    #   - /var/lib/postgresql:/var/lib/postgresql
  db_gui:
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  # client:
  #   container_name: react
  #   build: ./client
  #   image:
    # ports:
    #   - '27017:27017'