version: '3'
services:
  api:
    container_name: fatboar-back-dev
    image: fatboar-back-dev
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - './api:/usr/src/app'
      - 'node_modules_back:/usr/src/app/node_modules'
    ports:
      - '5000:3000'
      - '9229:9229'
    depends_on:
      - postgres-db
    networks:
      - fatboar-dev
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
      - TEST_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/fatboar-test
      - JWT_SECRET=${JWT_SECRET}
    command: npm run start:dev
    restart: always
  postgres-db:
    container_name: fatboar-db-dev
    ports:
      - "5432:5432"
    networks:
      - fatboar-dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  db_gui:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres-db
    networks:
      - fatboar-dev
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    logging:
      driver: "none"
    restart: always
  client:
    container_name: fatboar-front-dev
    image: fatboar-front-dev
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - './client:/usr/src/app'
      - 'node_modules_front:/usr/src/app/node_modules'
    environment: 
      - NODE_PATH=.
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - '3000:3000'
    restart: always
networks:
  fatboar-dev:
volumes:
  pgdata: