version: '3'
services:
  api:
    image: fatboar-back-dev
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - './api:/usr/src/app'
      - 'node_modules_back:/usr/src/app/node_modules'
    ports:
      - '5000:3000'
      - '9229:9229'
    command: nodemon -L index.js
  postgres-db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgresql:/var/lib/postgresql
  db_gui:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres-db
    networks:
      - web
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  client:
    image: fatboar-front-dev
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - './client:/usr/src/app'
      - 'node_modules_front:/usr/src/app/node_modules'
    ports:
      - '3000:3000'