version: '3'
services:
  api:
    depends_on:
      - postgres-db
    networks:
      - web
  postgres-db:
    hostname: postgres
    image: postgres:11.5-alpine
  client:
    networks:
      - web
networks:
  web:
    external:
      name: web
volumes:
  node_modules_back:
  node_modules_front: