FROM node:carbon

# Set user
# USER node

# install dependencies
WORKDIR /usr/src/app

# Install nodemon for hot reload
RUN npm install -g nodemon

COPY package*.json ./

# RUN npm install

# RUN if [ "$NODE_ENV" = "development" ]; \
# 	then npm install;  \
# 	else npm install --only=production; \
# 	fi
RUN npm cache clean --force && npm install

COPY . /usr/src/app

ENV PORT 3000

EXPOSE 3000

#CMD ../scripts/start.sh

CMD [ "nodemon", "index.js" ]
# CMD [ "npm", "run", "start" ]